### ISSUE TITLE
Images Matched, then now seen as unmatching

### ISSUE THREAD

**Issue by invious** [ppwwyyxx/panorama#13]
I was able to stitch these two images together, using Translation mode and Ordered Input,

<img width="390" alt="5" src="https://cloud.githubusercontent.com/assets/1996089/16453419/cec2878c-3dda-11e6-964f-9644ec0f0fc3.png">
<img width="388" alt="6" src="https://cloud.githubusercontent.com/assets/1996089/16453423/d0e47ad4-3dda-11e6-9775-c66d56f9fdc6.png">
## This successfully gave me out.jpg at first...

and then I ran the program again anding the images don't match! I didn't change anything between runs!

![image](https://cloud.githubusercontent.com/assets/1996089/16453463/eed97558-3dda-11e6-8590-02b74759d0fe.png)

**Comment by invious** [comment]
I just ran the software 4 times consecutively, and it worked one time... very inconsistent, why?

![image](https://cloud.githubusercontent.com/assets/1996089/16456685/b587e71a-3de6-11e6-86b3-d7655d15c740.png)

it finally worked once, but I have no idea why it's failing most of the time?

![out](https://cloud.githubusercontent.com/assets/1996089/16456721/e154e366-3de6-11e6-95b6-1eeb3bc2ef10.jpg)

**Comment by ppwwyyxx** [comment]
There are some randomness in the matching algorithm so I'm not surprised.
Also, this two images doesn't overlap at all, so you shouldn't expect it to produce anything meaningful results.

**Comment by invious** [comment]
they do overlap, and it work!

[image: Inline image 3]

but ok, I will just execute it over and over until it works I suppose

On Wed, Jun 29, 2016 at 4:53 PM, Yuxin Wu <notifications@github.com> wrote:

> There are some randomness in the matching algorithm so I'm not surprised.
> Also, this two images doesn't overlap at all, so you shouldn't expect it
> to produce anything meaningful results.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ppwwyyxx/panorama/issues/13#issuecomment-229485277>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AB51Oe6EPRPIc8nXlWAhwROhrkkdqcBPks5qQttKgaJpZM4JBIFY>
> .
>



-- 
LinkedIn <https://www.linkedin.com/in/invious> | StackOverflow
<http://stackoverflow.com/users/325081/aymon-fournier?tab=profile> | Github
<https://github.com/invious> | Twitter <https://twitter.com/BeInvious> |
Facebook <https://www.facebook.com/BeInvious> | Medium
<https://medium.com/@aymon>

**Comment by ppwwyyxx** [comment]
Oh I thought the two images are the smaller screenshot and the larger one.
I tested on your images, and it found a lot of point-wise matches of the same letter because each letter appear in different places and they do look identical indeed, so it is very hard to find a geometrically-consistent global match. 
This program is actually intended for scene (fewer repeated identical patches) rather than text.

**Comment by invious** [comment]
It works sometimes with some settings.. is there any way to use your code
with certain settings to stitch together screenshots? This is my goal, and
it seems to work sometimes but not always. As it is now I will simply run
the binary over and over until it successfully identifies overlapping areas

On Wed, Jun 29, 2016 at 6:41 PM, Yuxin Wu <notifications@github.com> wrote:

> Oh I thought the two images are the smaller screenshot and the larger one.
> I tested on your images, and it found a lot of point-wise matches of the
> same letter because each letter appear in different places and they do look
> identical indeed, so it is very hard to find a geometrically-consistent
> global match.
> This program is actually intended for scene (fewer repeated identical
> patches) rather than text.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ppwwyyxx/panorama/issues/13#issuecomment-229510995>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AB51OUuA2U3JL3gShT15Bzdr_iPflgBRks5qQvSegaJpZM4JBIFY>
> .
>



-- 
LinkedIn <https://www.linkedin.com/in/invious> | StackOverflow
<http://stackoverflow.com/users/325081/aymon-fournier?tab=profile> | Github
<https://github.com/invious> | Twitter <https://twitter.com/BeInvious> |
Facebook <https://www.facebook.com/BeInvious> | Medium
<https://medium.com/@aymon>

**Comment by ppwwyyxx** [comment]
Presumably one way to achieve this is to setup a region in each image to detect key points, and ignore key points outside the range. This could avoid matching too many unexpected letters.

**Comment by invious** [comment]
This is way out of my field of study, but if your software can be tweaked,
or if there are settings that can be used with your existing software, I
would love to include it in the project I intend to build to quickly stitch
screenshots

On Thu, Jun 30, 2016 at 3:19 PM, Yuxin Wu <notifications@github.com> wrote:

> Presumably one way to achieve this is to setup a region in each image to
> detect key points, and ignore key points outside the range. This could
> avoid matching too many unexpected letters.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ppwwyyxx/panorama/issues/13#issuecomment-229761090>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AB51OdcHAveC2XeeiFlq2J8vadzA_hbcks5qRBavgaJpZM4JBIFY>
> .
>



-- 
LinkedIn <https://www.linkedin.com/in/invious> | StackOverflow
<http://stackoverflow.com/users/325081/aymon-fournier?tab=profile> | Github
<https://github.com/invious> | Twitter <https://twitter.com/BeInvious> |
Facebook <https://www.facebook.com/BeInvious> | Medium
<https://medium.com/@aymon>
