### ISSUE TITLE
how to run this demo on windows vs?

### ISSUE THREAD

**Issue by zhangyunming** [ppwwyyxx/panorama#15]
hi,thank you for the  great job.

now ,i want to run this work on windows vs2013,can you give some advice?

best wishes!

**Comment by ppwwyyxx** [comment]
I've never tried windows so I have no idea. People have successfully compiled it in windows and contribute a CMakeLists.txt which should work.

However vs2013 seems too old, according to the CMakeLists.txt

**Comment by xiaoyan-hou** [comment]
Can  the one who  run this demo on windows vs   successfully ， description the procedure  ? very  thanks

**Comment by xiaoyan-hou** [comment]
I run this work on windows  successfully ,so, maybe i can give you some advice

**Comment by bitdelve** [comment]
> I run this work on windows successfully ,so, maybe i can give you some advice

I want to do the same thing. Can you give some tips please?

Thanks

**Comment by xiaoyan-hou** [comment]
首先用vs编译libjpeg，把编译好的文件和jepg.h文件，放入src文件夹，同时下载Eigen库，也放入src文件夹，然后用cmake和vs13编译src源文件，用vs15打开生成的工程





At 2016-11-18 04:28:16, "bitdelve" <notifications@github.com> wrote:


I run this work on windows successfully ,so, maybe i can give you some advice

I want to do the same thing. Can you give some tips please?

Thanks

**Comment by xiaoyan-hou** [comment]
如果还有什么错误，可以联系我的qq，1375104686





At 2016-11-18 04:28:16, "bitdelve" <notifications@github.com> wrote:


I run this work on windows successfully ,so, maybe i can give you some advice

I want to do the same thing. Can you give some tips please?

Thanks

**Comment by ppwwyyxx** [comment]
Now the cmake build process is fixed, (thanks to @ChenXiaoTemp #26 ). You can build it in VS2015 with the steps in README.
