### ISSUE TITLE
images not match

### ISSUE THREAD

**Issue by meifen** [ppwwyyxx/panorama#17]
Hi,thanks for your kind to share the code. it makes good quality and amzing speed when using the example data,but it always report images not match issue when using images that captrued by my phone, though the images have overlap area. what can i set for this issue?

**Comment by jounih** [comment]
For panoramic images, you need to rotate the camera on the no-parallax axis - ie keep it static while turning it around. Otherwise you will get stitching errors

**Comment by ppwwyyxx** [comment]
Yes you need to keep it static while turning the camera. I just added some quality guidelines in readme.md.
