### ISSUE TITLE
Motion model with both translation and rotation

### ISSUE THREAD

**Issue by skruzic** [ppwwyyxx/panorama#18]
Hi,

is it possible to use this app for stitching aerial images taken with UAV to produce map-like panoramas (or mosaics, whichever is the right word).
I tried with OpenCV, but that's not possible because it only uses model with pure rotation. Since this model can also use translation, is it possible to combine those two?

Thanks!

**Comment by ppwwyyxx** [comment]
This project also only dealt with pure rotation. To produce a mosaic with translation+rotation doesn't make a perfect sense mathematically, because there is not a single projection center.
