### ISSUE TITLE
fix the stitch parameter

### ISSUE THREAD

**Issue by xuzero** [ppwwyyxx/panorama#19]
Thanks for your share!
i have run my images successfully configured with the mode CYLINDER which is better than mode ESTIMATE_CAMERA. i want to fix the stitch parameter in order that the following image sets stitch with the same parameter and output the same panorama size.
Would you like to tell me how to get the stitch parameter with the mode CYLINDER ?
Thanks!

**Comment by ppwwyyxx** [comment]
You can load a pre-computed `bestfactor` at [this line](https://github.com/ppwwyyxx/panorama/blob/master/src/stitch/cylstitcher.cc#L63),
and load a pre-computed `bundle.component[]` array at [this line](https://github.com/ppwwyyxx/panorama/blob/master/src/stitch/cylstitcher.cc#L86).
This way the output should be rendered using the same settings.
