### ISSUE TITLE
这是什么问题  能帮我看看吗

### ISSUE THREAD

**Issue by Othway** [ppwwyyxx/panorama#20]
hello，ppwwyyxx
I yet installed libjpeg,but when i run it,there some questions;
root@ubuntu:/home/tirvideo/panorama-master/panorama-master/src# ./image-stitching <medium00><medium01>
bash: In the unexpected "<" syntax error near
how can i solve it？
thank you
best wishes

**Comment by ppwwyyxx** [comment]
I don't think you have copied the complete command and error. Could you provide more details?
