### ISSUE TITLE
difference between CYLINDERand ESTIMATE_CAMERA

### ISSUE THREAD

**Issue by xuzero** [ppwwyyxx/panorama#21]
I only know that CYLINDER  require the order input and generate the better panorama and also
cost the longer time.If not right, please correct!
Could you please explain difference between CYLINDER and ESTIMATE_CAMERA  in principle?
 Thanks!

**Comment by ppwwyyxx** [comment]
It may or may not generate better results or cost more time. It usually depends on the data.
Section 3 and 4 of [my blog article](http://ppwwyyxx.com/2016/How-to-Write-a-Panorama-Stitcher/#Cylindrical-Panorama) explains the algorithms in the two mode.
