### ISSUE TITLE
How to get apple.jpg?

### ISSUE THREAD

**Issue by guohengkai** [ppwwyyxx/panorama#22]
How to get apple.jpg, which is a 720 panorama?

Thanks.

**Comment by ppwwyyxx** [comment]
`./image-stitching planet ../results/CMU0-all.jpg`

**Comment by guohengkai** [comment]
Thank you!

**Comment by xiaoyan-hou** [comment]
what is the  differences  of stitch mode  between CMU0-all.jpg and   apple.jpg   ?  I mean  they have the same  source images ,but  the result is totally different ?
