### ISSUE TITLE
popen/pclose was not declared

### ISSUE THREAD

**Issue by bitdelve** [ppwwyyxx/panorama#23]
I am trying to build this in cygwin. I have gotten stuck at the errors of both popen and pclose was not declared in this scope. This is within the CImg.h class. 

Any ideas?

**Comment by ppwwyyxx** [comment]
Sorry but I'm not familiar with windows, and the code is in CImg so I have no idea.

**Comment by bitdelve** [comment]
Can you tell me what setup you are using? Maybe if I have the same setup it will work fine.

**Comment by ppwwyyxx** [comment]
What do you mean by setup? I didn't use windows/cygwin so my experience won't help much.
http://stackoverflow.com/questions/22166633/mingw-function-not-found-when-compiled-with-std-c11 This seems related.

**Comment by bitdelve** [comment]
Thanks for the link. I finally got it working through the Ubuntu Bash beta on Windows 10.

**Comment by ppwwyyxx** [comment]
Great! That's good to know.
