### ISSUE TITLE
How can only be modified to achieve real-time stitching

### ISSUE THREAD

**Issue by Othway** [ppwwyyxx/panorama#25]
Hi ...
For the time I look at your code ...There are some doubts can you help? I have readed your blog,I found the trans mode for onebyone stitching is better，at your blog you said it only applicable when camera do pure translation，but when I used some rotate pictures, It sames work good, because of  it?(The skew factor in homography (H31,H32) cannot be too large. Their absolute values are usually less than 0.002.) can i understand for some slight rotate it can work，It is the real-time first... Thank you (I had used GPU accelerate，there are only 100mills for two 600*400 pictures)

**Comment by ppwwyyxx** [comment]
I don't understand what you're asking.
And TRANS mode may be better if there is only very small rotation -- if that's what you're asking.

**Comment by Othway** [comment]
Sorry,You're talking about what I mean..In this mode,when i enter all the pictures to be stitched,it worked well. if one  by one to stitch it always failed at fourth or fifth pictures...it  is now my biggest problem facing stitching
