### ISSUE TITLE
camera_estimator mode是不是类似于相机标定  

### ISSUE THREAD

**Issue by Othway** [ppwwyyxx/panorama#27]
你好，我想问下这个模式有没有去除相机畸变

**Comment by ppwwyyxx** [comment]
没有

**Comment by Othway** [comment]
蟹蟹  如果加上相机矫正的话是不是对近一点的目标拼接效果会好一点，你看看我加了畸变和不加畸变拼出来的效果。

![out2](https://cloud.githubusercontent.com/assets/19154155/21215436/3dd9ba06-c2dc-11e6-88f5-9177296afc02.jpg)
![pano35](https://cloud.githubusercontent.com/assets/19154155/21215437/3e7bed94-c2dc-11e6-8483-edfcde86dde9.jpg)
![pano31](https://cloud.githubusercontent.com/assets/19154155/21215500/a0a190dc-c2dc-11e6-9d9d-36e02c43e511.jpg)
![pano34](https://cloud.githubusercontent.com/assets/19154155/21215501/a1244586-c2dc-11e6-9d77-3f4cedf81d00.jpg)

**Comment by ppwwyyxx** [comment]
是的

**Comment by Othway** [comment]
谢谢
