### ISSUE TITLE
Documentation doesn't mention ImageMagick

### ISSUE THREAD

**Issue by NoGare** [ppwwyyxx/panorama#28]
Hello,

When doing a fresh install attempts to run ./image-sticher fail with the below error, this can be rectified by installing 'imagemagick' (i.e. `sudo apt install imagemagick`).

$ ./image-stitching medium01.jpg medium02.jpg medium03.jpg

> [init_config@main.cc:252] Run with camera estimation mode.
> sh: 1: sh: 1: sh: 1: convert: not found
> ./convert: not found
> ./convert: not found
> sh: 1: gm: not found
> sh: 1: gm: not found
> sh: 1: gm: not found
> sh: 1: convert: not found
> sh: 1: convert: not found
> sh: 1: convert: not found
> sh: 1: gm: not found
> sh: 1: gm: not found
> sh: 1: gm: not found
> sh: 1: convert: not found
> sh: 1: convert: not found
> sh: 1: convert: not found
> sh: 1: gm: not found
> 
> [CImg] *** CImgIOException *** [instance(0,0,0,0,(nil),non-shared)] CImg<unsigned char>::load(): Failed to recognize format of file 'medium02.jpg'.
> sh: 1: gm: not found
> terminate called after throwing an instance of 'cimg_library::CImgIOException'
> 
> [CImg] *** CImgIOException *** [instance(0,0,0,0,(nil),non-shared)] CImg<unsigned char>::load_pnm(): PNM header not found in file '(FILE*)'.
>   what():  [instance(0,0,0,0,(nil),non-shared)] CImg<unsigned char>::load(): Failed to recognize format of file 'medium02.jpg'.
> sh: 1: gm: not found
> Aborted (core dumped)

Thank you for releasing this software, it's proved a great tool for me to learn. 

Regards

**Comment by ppwwyyxx** [comment]
This is because you didn't have libjpeg but tried to read jpeg files. When libjpeg is missing, it will try to use imagemagick to read images (which is slow).

**Comment by NoGare** [comment]
Hrm... That's odd. 

I thought I had installed it; my mistake.

**Comment by lucychen0103** [comment]
@NoGare @ppwwyyxx How do you install libjpeg to read your files?
