### ISSUE TITLE
How to run the CYLINDER mode

### ISSUE THREAD

**Issue by tianboguangding** [ppwwyyxx/panorama#9]
hi, thanks for your shared panarama-stitching

 when I run the image-stitching as followed:

wqy@wqy-Precision-T3600:~/Desktop/panorama-master/src$ ./image-stitching  ../data/apartment/small-01.jpg ../data/apartment/small-02.jpg
[init_config@main.cc:271] Run with camera estimation mode.
sh: 1: convert: not found
sh: 1: gm: not found
sh: 1: convert: not found
sh: 1: gm: not found
sh: 1: convert: not found
sh: 1: gm: not found

[CImg] *** CImgIOException *** [instance(0,0,0,0,(nil),non-shared)] CImg<float>::load(): Failed to recognize format of file '../data/apartment/small-01.jpg'.
terminate called after throwing an instance of 'cimg_library::CImgIOException'
  what():  [instance(0,0,0,0,(nil),non-shared)] CImg<float>::load(): Failed to recognize format of file '../data/apartment/small-01.jpg'.
Aborted (core dumped)

So how do I use it?
Thanks very much!

**Comment by ppwwyyxx** [comment]
To read jpeg file you need to install libjpeg-dev (name may be different on different platforms).

**Comment by tianboguangding** [comment]
I have installed the libjpeg-dev, bue the same question is occurred

**Comment by ppwwyyxx** [comment]
It's my fault. The latest commit should fix this.
Install imagemagick can also solve your problem.

**Comment by tianboguangding** [comment]
Thanks !It worked . 
Sorry,but one more question, How to switch the different mode in the config.cfg?
For example :the occurred global palyground Image

**Comment by ppwwyyxx** [comment]
Just set one of 'CYLINDER', 'ESTIMATE_CAMERA', 'TRANS' to 1 in config.cfg and run the program.

**Comment by tianboguangding** [comment]
No matter which mode was set to one , the running result of your apartment images is rectangle all the time,but not spherical(circular image)

**Comment by ppwwyyxx** [comment]
The mode is for different kind of algorithm. The spherical example is not a mode, just something fun. And it's easy to convert the 360 degree rectangle panorama to a spherical one.

It's likely that your images doesn't overlap enough (you can look at the example images to see what kind of overlap is needed). You can also post your log here.

**Comment by tianboguangding** [comment]
Thanks very much!
Now i  complie your project in vs 2015, the error log is as followed:

[32m[init_config@:267] [0mRun with cylinder mode.
无效参数 - /github
'gm.exe' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
无效参数 - /github
'gm.exe' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
无效参数 - /github
'gm.exe' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

[CImg] *** CImgIOException *** [instance(0,0,0,0,0000000000000000,non-shared)] CImg<float>::load(): Failed to recognize format of
file 'D:/github/panorama/1/panorama-master/src/build/Debug/976.jpg'.
 
it seems to the same error with the linux's.
 should i still install the window's version of imagemagick ?

**Comment by ppwwyyxx** [comment]
Seems like you're not compiling with the latest commit 877327042a8729498188e0d494d17b8546a3f72f? 
convert or gm will only be used when CImg cannot use libjpeg.

Also it could be easier if you just use png files. png reader/writer are already included in the project.

**Comment by tianboguangding** [comment]
Thanks for your answer!
But After   plus the #define cim_use_jpeg in the .c file (imgio.cc), the project even can not to be compilied successfully ! And the log is as followed：

.......
1>jpeg.lib(jerror.obj) : error LNK2001: unresolved external symbol __imp___iob_func
1>D:\github\panorama\1\panorama-master\src\build\Debug\image_stitching.exe : fatal error LNK1120: 1 unresolved externals
========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========

**Comment by ppwwyyxx** [comment]
That looks like a problem with your jpeg library. Unfortunately I've no idea where to find a jpeg library for windows.

Some google search suggest the reason is that your jpeg library is probably built with an old version of visual studio: http://stackoverflow.com/questions/30412951/unresolved-external-symbol-imp-fprintf-and-imp-iob-func-sdl2

**Comment by tianboguangding** [comment]
Thanks for your help!
Now it worked!

Have you considered a parallel algorithm(eg:cuda for sift) of stitching img  in order to  improve the speed?

**Comment by ppwwyyxx** [comment]
Right now it is parallel across the images in most steps. Cuda will definitely make it faster but I won't have time for that in the near future.

**Comment by tianboguangding** [comment]
Thanks for your reply :)
